#############################
# Notify submodule updates to repo
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
#############################
name: Notify submodule updates

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          repository: ${{ vars.PARENT_REPO }}
          token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}
          submodules: recursive

      - name: Update Submodule
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Commit
        run: |
          git status
          git config user.email ${{ vars.USER_EMAIL }}
          git config user.name "GitHub Actions"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push
